# ===============================
# APPLICATION
# ===============================
spring.application.name=Uber-bookaro

# ===============================
# DB CONFIG (NEON POSTGRES)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-proud-cherry-aok96g3v-pooler.c-2.ap-southeast-1.aws.neon.tech/Uber-bookaro?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7JgxwREnsjr4

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# DATA INITIALIZATION
# ===============================
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# ===============================
# CONNECTION POOL
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

# ===============================
# SECURITY
# ===============================
jwt.secretKey=eoichqojcoqwcjomcowjcomqcjqpcjqmcqncoqnc

# ===============================
# SMTP CONFIG
# ===============================
spring.mail.host=localhost
spring.mail.port=1025

# ===============================
# SERVER
# ===============================
server.port=8080